
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.5'
version_full = 'b8f4c6f4dac8e7ae395dbf2dd67b4212b34e304a'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

